name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g imagemin-cli
          npm install -g imagemin-mozjpeg
          npm install -g imagemin-pngquant

      - name: Debug directory
        run: |

          echo "Creating directories."
          mkdir -p optimized-images
          pwd
          echo "Contents before:"
          ls -la
          echo "Images directory:"
          ls -la images || echo "No images directory in root"

      - name: Optimize images
        run: |
          mkdir -p optimized-images
          if [ -d "images" ]; then
            for img in images/*; do
              if [ -f "$img" ]; then
                echo "Optimizing: $img"
                imagemin "$img" --out-dir=optimized-images
              fi
            done
          else
            echo "Warning: images directory not found"
            echo "Current location:"
            pwd
            echo "Directory contents:"
            ls -la
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
