name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add explicit permissions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g imagemin-cli
          npm install -g imagemin-mozjpeg
          npm install -g imagemin-pngquant

      - name: Create directories
        run: mkdir -p optimized-images

      - name: Optimize images
        run: |
          if [ -d "images" ] && [ "$(ls -A images)" ]; then
            imagemin images/* --out-dir=optimized-images \
              --plugin.mozjpeg.quality=80 \
              --plugin.pngquant.quality=[0.6,0.8]
          else
            echo "No images found to optimize"
          fi

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
